Switch from downloadjs to multi-download (#174)
* Delete FUNDING.yml

* fix: docker-compose now 

- docker-compose version 1.29.2, build unknown
- Linux 5.15.0-1029-oracle #35-Ubuntu SMP Tue Jan 24 15:17:52 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

```
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.blaze-server.environment.TRUST_PROXY contains true, which is an invalid type, it should be a string, number, or a null
```

* Migrate to GA4

Universal Analytics has been shut down

* Switch from downloadjs to multi-download

* Move to utils/download.js

* Amend comment

* Add URL.revokeObjectURL

* Simplify delay behaviour, add JSDoc comments

* Typo

* Fix typo

* Fix multi-file downloads for WebTorrent

* Update client/src/utils/download.js

Co-authored-by: ddelange <14880945+ddelange@users.noreply.github.com>

---------

Co-authored-by: Akash Hamirwasia <akash.hamirwasia@gmail.com>
Co-authored-by: 薛定谔的meow <42793079+ruoduan-hub@users.noreply.github.com>
Co-authored-by: Akash Hamirwasia <akash@elevenlabs.io>